Parse GitHub details using origin remote.

diff --git a/test/bin/generate-sha256 b/test/bin/generate-sha256
--- a/test/bin/generate-sha256
+++ b/test/bin/generate-sha256
@@ -1,9 +1,30 @@
 #!/usr/bin/env bash
 # Generate SHA256 of a git ref, defaulting to current git HEAD.
 #
-# See README caveats of GitHub's tarball mismatch with output SHA256.
+# See README caveats of GitHub's tarball SHA256.
 
-GITHUB_USER=${GITHUB_USER:-rduplain}
+# Exit immediately if a command error or non-zero return occurs.
+set -e
+
+# The name of this executable program.
+PROG="$( basename "${BASH_SOURCE[0]}" )"
+
+given() {
+    # Check that the given commands exist.
+
+    local error=''
+
+    for command in "$@"; do
+        if ! which "$command" > /dev/null; then
+            echo "$PROG requires '$command' command, but cannot find it." >&2
+            error=true
+        fi
+    done
+
+    if [ -n "$error" ]; then
+        return 3
+    fi
+}
 
 dirty() {
     # Check if git repository is dirty, return zero if dirty.
@@ -21,7 +42,7 @@ dirty() {
 
 }
 
-warn-if-dirty() {
+warn-if-dirty-head() {
     # Warn to stderr if target ref is HEAD and working tree is dirty.
 
     if [ $# -ne 1 ]; then
@@ -52,8 +73,20 @@ generate-sha256() {
     local ref="$1"
     shift
 
+    local url=$(git remote get-url origin)
+
+    if [ -z "$url" ] || [ "${url//github/}" = "${url}" ]; then
+        echo "Remote 'origin' is not GitHub: $url" >&2
+        return 1
+    fi
+
+    local github_user=$(echo ${url} | awk -F '[/:]' '{ print $(NF-1) }')
+    local github_project_git=$(echo ${url} | awk -F '[/:]' '{ print $NF }')
+    local github_project=${github_project_git%%.git}
+
+    # Again... See README caveats of GitHub's tarball SHA256.
     git archive \
-        --prefix=${GITHUB_USER}-Makefile.d-"$ref"/ \
+        --prefix=${github_user}-${github_project}-"$ref"/ \
         --format=tar.gz -6 "$ref" |\
             openssl dgst -sha256 |\
                 awk '{ print $2 }'
@@ -62,17 +95,18 @@ generate-sha256() {
 main() {
     # Main.
 
+    given awk git openssl
+
     if [ $# -gt 0 ]; then
         target_ref=$1
     else
         target_ref=HEAD
     fi
 
-    warn-if-dirty "$target_ref"
+    warn-if-dirty-head "$target_ref"
 
     ref=$(git rev-parse --short $target_ref)
 
-    # Again... See README caveats of GitHub's tarball mismatch with output SHA256.
     echo    "ref:    $ref"
     echo -n "sha256: "
     generate-sha256 "$ref"
